### ISSUE TITLE
Championship Checklist

### ISSUE THREAD

**Issue by chacha** [Team3128/info#10]
Here are all the things that we need to finish before Championship:

## Administrative Tasks
For @chacha unless otherwise noted.

- [x] Find Teacher
- [x] Book Flights
- [x] Reserve Hotels
- [x] Submit School District Paperwork
- [x] Finish Travel Budget + Email
- [x] Create Trip Itinerary
- [x] Arrange Drop-Off/Pick-Up Carpools
- [x] Send Rooming List to Hotel
- [ ] Pack Robot Lockout Form
- [ ] Pack MetroPasses
- [x] Print Field Trip Permission Forms

## Shipping Robot

- [x] Submit Shipping Information (@Chacha)
- [x] CAD Crate (@FreezingClouds) 
- [x] Buy Crate Materials (@Garrison-Price)
- [x] Build Crate (@Garrison-Price) 
- [x] Receive Shipping Documents (@Chacha)
- [x] Arrange FedEx Pickup (@Chacha)
- [x] Ship Crate (@Chacha)

## Build Tasks

- [ ] Create Packing List 

## Marketing

- [x] Make Narwhal Horns (@MayaZivi)

**Comment by chacha** [comment]
Submitted District Paperwork to Bernard. Should be sent to the district on Monday.

**Comment by chacha** [comment]
We still need to find and/or replace the Robot Lockout Form. If we can't find it, the non-compliance form is online.

**Comment by chacha** [comment]
@Garrison-Price arranged for FedEx pickup between 4p and 6pm on Tuesday, April 12th.

**Comment by chacha** [comment]
Submitting Badging Roster for Championships. Currently we have 35 people in attendance.
